'\" t
.\"     Title: policy.py
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/16/2011
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "POLICY\&.PY" "5" "02/16/2011" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
policy.py_ \- zorp(8) policy file\&.
.SH "DESCRIPTION"
.PP
The
policy\&.py
file is a Python module containing the zone and service definitions and other policy related settings used by
\fBzorp(8)\fR\&. Empty lines and lines beginning with \*(Aq#\*(Aq are comments and are ignored\&.
.PP
The
policy\&.py
file is generated automatically by ZMC, the Zorp Management Console, or it can be edited manually\&.
.PP
IMPORTANT: Do not edit manually a file generated by ZMC, because the manual changes will not be retained by ZMC and will be lost when re\-generating the file\&.
.SH "FILES"
.PP
The default location of
policy\&.py
is
/etc/zorp/policy\&.py\&.
.SH "SEE ALSO"
.PP
For further information on
policy\&.py
refer to the following sources:
.PP
A tutorial on manually editing the
policy\&.py
file can be found at
\m[blue]\fBhttp://www\&.balabit\&.com/network\-security/zorp\-gateway/gpl/tutorial/\fR\m[]\&\s-2\u[1]\d\s+2\&.
.PP
Additional information can also be found in the
\fIZorp Administrator\*(Aqs Guide\fR, the
\fIZorp Reference Guide\fR, and in the various tutorials available at the BalaBit Documentation Page at
\m[blue]\fBhttp://www\&.balabit\&.com/support/documentation/\fR\m[]\&\s-2\u[2]\d\s+2\&.
.SH "AUTHOR"
.PP
This manual page was written by the BalaBit Documentation Team <documentation@balabit\&.com>\&.
.SH "COPYRIGHT"
.PP
Copyright \(co 2006 BalaBit IT Security Ltd\&. All rights reserved\&. For more information about the legal status of this document please read:
\m[blue]\fBhttp://www\&.balabit\&.com/products/zorp/docs/legal_notice\&.bbq\fR\m[]
.SH "NOTES"
.IP " 1." 4
http://www.balabit.com/network-security/zorp-gateway/gpl/tutorial/
.RS 4
\%http://www.balabit.com/network-security/zorp-gateway/gpl/tutorial/
.RE
.IP " 2." 4
http://www.balabit.com/support/documentation/
.RS 4
\%http://www.balabit.com/support/documentation/
.RE
